title: ProgTime
description: A blog about programming and technology.
baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-feed

show_excerpts: true

header_pages:
  - about.md

# Social links
social:
  github: https://github.com/prog-time
  telegram: https://t.me/iliyalyachuk
  youtube: https://youtube.com
