title: ProgTime
description: A blog about programming and technology.
baseurl: ""
url: ""

theme: minima

plugins:
  - jekyll-feed

show_excerpts: true

collections:
  projects:
    output: true
    permalink: /projects/:name/
  jobs:
    output: true
    permalink: /experience/:name/

header_pages:
  - about.md

# Social links
social:
  github: https://github.com/prog-time
  telegram: https://t.me/iliyalyachuk
  youtube: https://youtube.com
